# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
     add_comment:
         class: TestAppBundle\Service\AddComment
         arguments: ["@doctrine.orm.entity_manager", "@logger","@router"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
